{% set name = "portend" %}
{% set version = "2.7.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "986ed9a278e64a87b5b5f4c21e61c25bebdce9919a92238d9c14c37a7416482b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
    - setuptools_scm >=3.4.1

  run:
    - python >=3.6
    - tempora >=1.8

test:
  imports:
    - portend

about:
  home: https://github.com/jaraco/portend
  # license_file: No license or manifest - see https://github.com/jaraco/portend/issues/3
  license: MIT
  license_family: MIT
  summary: TCP port monitoring utilities
  dev_url: https://github.com/jaraco/portend

extra:
  recipe-maintainers:
    - pmlandwehr
