{% set name = "portend" %}
{% set version = "2.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "bc48d3d99e1eaf2e9406c729f8848bfdaf87876cd3560dc3ec6c16714f529586" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm >=1.15.0

  run:
    - python
    - tempora >=1.8

test:
  imports:
    - portend

about:
  home: https://github.com/jaraco/portend
  # license_file: No license or manifest - see https://github.com/jaraco/portend/issues/3
  license: MIT
  license_family: MIT
  summary: TCP port monitoring utilities
  dev_url: https://github.com/jaraco/portend

extra:
  recipe-maintainers:
    - pmlandwehr
