travis:
  secure:
    BINSTAR_TOKEN: m5wRBGBRJkk6WNygrloG56rG7rAWUhjzADeYmnSYDgEScK92d40FUxVs91bA++MYueEB2JMwwrMoFNxOmaTd5F6iz9vhXVv3FcZohk/KtYFfCoCvS18oTpIwi/05Ojs/O1QvZYzPk+2yaSgE07EtEhK55TdkE/yklOw12JvoOFycZwq5irsarxA1qioS7t+IJ4vgH8+wGUpYBqO97GJSju17FvmFthp9u70fibFDFKm/nbR7IatZ8URRbwww+6ncN9cjhsk3xqRe0YOogMKpHK0HSDBmJynBGZF0Zmc5gwV8OmlQA0oiSZOor+g9saYCTlZ0ttyxXapdzT58526Gu6LsPA4m1QQOSdLRItYZseNtPsXLvPrwkdi/9LZCEgdmIr+0g56mh01tGeNPeEqFl8QwMV33n61sUCs1J48YmZAzTGbrWnHZH0BsuqmLYDNk2Otohs6XzVjS1qWVAFe4Jk6aPNc1264mVCe6Kdsqy2RgacdNsRwmnUvSkBhbMfnI6GZjUXSaoflBHGm9O/Ro2kdBgN4bu6DGbTPd0qS5DnnRAy+zUOX5ideWj3pGcInzyhmsWZx8cW9nVpfovcUBaIaSQmZPnVnCaJC/HWvo8BevdNSB4ZFlHBetkrJAhQavlB9Q5DVD2yoYs1bzYutOmixt0vKGE2bwwxUHIQrIzL8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
