travis:
  secure:
    BINSTAR_TOKEN: T1SWhBZb9tPqWTbMvWLD23Zqh3zBoLdfGyumtt/fnJNwKcqhXk3lDAzbm3yX9Zj4UoRmM6BFezIb4nKlhES0gNZFXr6Nj7kTqefeQ5s2GLXCFpt+576ud4bgCJxf7JRJqHgq+sc6NecbraHJC6OS6u5/xzOkvIE1fYtz553tcfXIKAlUEJD3votnrZw8R5kyGvXrCfGnJfDIKDivqNU6su7sSfz+ENSG9EFBIuuxzmuXxTntrelglH8DN0ar29xh/lhvotNz/Yuu32byAhyCNUBqz9SikoDsUH1cHEtnNwsPIkUqx9qpIAsynQQsMU+9RZMoBvJsuYuqnyis5aWefN0zajTRLbdLrJyNgq+DyO5xmsG8oZD2YxmMJKj15wXvPCGSmnts9JzvqW7Ns2zn05GSLvh9hBVZ+7XMmGwGP8aKCUR14rjkAq2PNNjNkiSoWyqlkRINtQvIhsi1whOVrfdtIrPPYaHHbT9gWncnb/juNkUKM5dLWlQ20QvVd4qLaYeraeO4YgIR3Azxk/pqaMFagGWZSsRhFcbcUXzeIHXoHRFceOof+sQCxrAZfeVhVkiUd8/66689jvlh/ydVlkuXwLuoQ/CtLeWLh9MSr0bGcSSOqRkLYn1vqKPJx1e7djz4j3M1UyFnlGoKozFZoslG48ZFz/43cF+v3F+MbnE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
